### ISSUE TITLE
not enough  input arguments

### ISSUE THREAD

**Issue by Sreevathsav1** [andylamp/moses#3]
When i run whatever code except comparision.m, it keeps showing not enough  input arguments... Can you please help me with that? I have a presentation tomorrw.

**Comment by andylamp** [comment]
sorry, the code as-is is designed to be called from `comparison.m`, if you need to run individual functions you need to refactor the code.

Thanks!

**Comment by Sreevathsav1** [comment]
Ok. But, how do i refactor the code?

**Comment by andylamp** [comment]
Sorry, as I said in the previous replies - it is provided as-is. I cannot provide support for that.
